### ISSUE TITLE
Reasoner error caused by use of non-simple object property in a cardinality restriction

### ISSUE THREAD

**Issue by dillerm** [OpenLHS/PDRO#10]
Both 'drug dispensing validity period specification' (PDRO:0000307) and 'drug prescription validity period specification' (PDRO:0000317) use the transitive object property 'has part' (BFO:0000051) in cardinality restrictions. Unfortunately, OWL 2 DL does not allow the use of transitive object properties in cardinality restrictions, which causes any OWL 2 DL reasoner to throw an error message or give you unexpected results when run on pdro.owl. 

The best way to fix this would probably be to remove the cardinality restrictions and just say, for example, for 'drug dispensing validity period specification' (PDRO:0000307):

- has part some 'ending validity temporal specification'
- has part some 'starting validity temporal specification'

**Comment by pfabry** [comment]
Sorry for the late answer. 
We are aware of the limitations of OWL 2 reasoning with complex properties and cardinality and it's quite a conundrum for us as we feel that the cardinality restrictions are very important in our model.
In addition, we are in the process of rewriting this ontology (as well as LABO and a few others) and we intend to publish new versions in the coming months with important changes in the ontology structure. Do you use PDRO and if so, what are your classes of interest?

**Comment by dillerm** [comment]
No worries! I'm actually not using PDRO at the moment, but am working on a review of ontologies related to environmental exposures and came across this issue in the process.
