### ISSUE TITLE
'role in human social processes' (OMRSE:00000024) has been deprecated and replaced

### ISSUE THREAD

**Issue by dillerm** [OpenLHS/PDRO#11]
In the future we plan on reaching out to developers of ontologies that import our classes to get their input prior to making such changes, but we have replaced this class with another one with the same label: 'role in human social processes' (OMRSE:00002072). The only change to the class was to the subClassOf axiom, which we changed from "inheres-in only human or organization" to "inhere-in only 'material entity'."

**Comment by pfabry** [comment]
Thank you for the update. 
As a side note, what are your reasons for creating a new class in this case? I understand that the new class keeps the same label, the same position in the taxonomy and differs  from the old one only by a more general definition and axiom (material entity vs (human or organisation)).

**Comment by dillerm** [comment]
@pfabry I think we were sticking a little too strictly to the idea that if you change an axiom, you should deprecate the class and create a new one in its place. In retrospect, the changes we made probably wouldn't have led to reasoning errors, therefore I think we could have gotten away with just editing the axiom on the original class.
