### ISSUE TITLE
pharmacy facility

### ISSUE THREAD

**Issue by mbrochhausen** [OpenLHS/PDRO#4]
I may have found an inaccuracy in PDRO:
 
The axiomatic definition of ‘pharmacy facility’ states:
 
(facility
and ('is owned by' some ('is bearer of' some 'health care provider organization role'))) or ('is administered by' some ('is bearer of' some 'health care provider organization role'))
 
I am not sure about the situation in other countries,  but in the US a single person could own and run a pharmacy. Based on that I want to suggest changing the axiom to:
 
(facility
and ('is owned by' some ('is bearer of' some ('health care provider organization role' OR ‘healthcare provider role’)))) ('is bearer of' some ('health care provider organization role' OR ‘healthcare provider role’)))
 
But maybe I am missing something?

**Comment by pfabry** [comment]
Thank you for your comment. However, the axiomatic definition you are referring to actually comes from the parent class 'health care facility' from the OMRSE ontology.
I think your axiom modification should be adressed directly to the OMRSE team as a health care facility could indeed be ran and owned by a single person.

**Comment by pfabry** [comment]
Closing issue as it is obsolete.
