### ISSUE TITLE
imports for IAO and RO core use broken URLs

### ISSUE THREAD

**Issue by turbomam** [OpenLHS/PDRO#5]
Hello, OpenLHS. I find your ontologies very useful, except you use invalid URLs for IAO and RO core.

in `https://raw.githubusercontent.com/OpenLHS/PDRO/master/pdro.owl`,

`<owl:imports rdf:resource="http://purl.obolibrary.org/obo/iao/iao-edit.owl"/>`
Should use http://purl.obolibrary.org/obo/iao.owl

and `<owl:imports rdf:resource="http://purl.obolibrary.org/obo/ro/core-subset.owl"/>`
Should use http://purl.obolibrary.org/obo/ro/core.owl

**Comment by pfabry** [comment]
Thank you for your comments. 
I will get back to you as soon as the imports are fixed.

**Comment by pfabry** [comment]
Imports sources have been updated + merged version available in root directory.

**Comment by turbomam** [comment]
thnks
