### ISSUE TITLE
PDRO cannot be parsed

### ISSUE THREAD

**Issue by matentzn** [OpenLHS/PDRO#7]
Loading pdro with ROBOT fails due to a missing import:

```
robot merge -I http://purl.obolibrary.org/obo/pdro.owl -o pdro.test.owl
Could not load imported ontology: <http://purl.obolibrary.org/obo/iao/iao-edit.owl> Cause: http://purl.oclc.org/obo/iao/iao-edit.owl
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
```

As part of an OBO wide push to more standardised quality control, we are trying to analyse all ontologies, see https://github.com/orgs/OBOFoundry/projects/6

**Comment by matentzn** [comment]
See also https://github.com/OpenLHS/LABO/issues/1

**Comment by pfabry** [comment]
cf. https://github.com/OpenLHS/LABO/issues/1

**Comment by pfabry** [comment]
Imports sources have been updated + merged version available in root directory.

**Comment by matentzn** [comment]
This is great, I have refreshed the dashboard!
http://dashboard.obofoundry.org/dashboard/index.html
